title: Ludovic Laffineur
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/www" # the subpath of your site, e.g. /blog
url: "https://ludoviclaffineur.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ludovic Laffineur # add your name
author-img: ludo_brun_detoure.png # add your photo
about-author: I am a tech builder focusing on developping products. # add description
social-twitter: ludolaffineur # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: ludoviclaffineur # add your Github handle
social-linkedin: llaffineur # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
